repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v0.13.1
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*/tests/.*

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        additional_dependencies: [
            flake8-absolute-import,
            flake8-black,
            flake8-blind-except,
            flake8-builtins,
            flake8-comprehensions,
            flake8-docstrings,
            flake8-mutable,
            flake8-print,
            flake8-quotes,
            flake8-tuple,
        ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
